[window]
opacity = 0.8
dynamic_title = true
dynamic_padding = true
# padding = { x = 2, y = 1 }

[font]
normal = { family = "JetBrains Mono Nerd Font" }
size = 11.75

[colors.primary]
background = "#050e15"

[colors.normal]
red     = "#ff5555"
green   = "#239c2b"
yellow  = "#f1fa8c"
blue    = "#1d83dc"
magenta = "#c792ea"
cyan    = "#89ddff"
white   = "#ffffff"

[colors.bright]
# yellow = "#ffe585"
# magenta = "#e1acff"
# cyan = "#a3f7ff"
# white = "#fefefe"
# green = "#23bC3B"

[keyboard]
bindings = [
  { key="X",  mods="Control | Shift", action="SpawnNewInstance" }
]

[cursor]
style = {shape = "Beam"}
thickness = 0.20

