[General]
__userfile__=true
icon_theme=breeze-dark
style=kvantum
tool_bar_icon_size=24
tool_button_style=ToolButtonTextBesideIcon

[Palette]
base_color=#071520
highlight_color=#3c8ce6
highlighted_text_color=#ffffff
link_color=#0000ff
link_visited_color=#ff00ff
text_color=#87a9bf
tooltip_base_color=#000000
tooltip_text_color=#d7f1f8
window_color=#efefef
window_text_color=#ffffff

[Qt]
font="JetBrains Mono NF,12"
style=kvantum
