inherits = "material_palenight"
"ui.background" = {}
"ui.linenr" = { fg = "#656580" }
"ui.cursor.normal" = { bg = "#8b8bab"}
"ui.cursor.insert" = { bg = "#8b8bdb"}
"ui.cursor.select" = { bg = "#8babab"}
