#!/bin/sh

# ANSI color scheme script featuring PACMAN
# Author: pfh
# Source: http://crunchbang.org/forums/viewtopic.php?pid=144481#p144481 
# Initializing procedure by lolilolicon
# Modified by: MarceliGG

rst=$'\e[0m'
col1=$'\e[31;1m'
col2=$'\e[32;1m'
col3=$'\e[33;1m'
col4=$'\e[34;1m'
col5=$'\e[35;1m'
col6=$'\e[36;1m'
col7=$'\e[37;1m'
col8=$'\e[30;1m'

cat << EOF

 $col3  ▄███████▄                $col1  ▄██████▄    $col2  ▄██████▄    $col4  ▄██████▄    $col5  ▄██████▄    $col6  ▄██████▄    
 $col3▄█████████▀▀               $col1▄$col7█▀█$col1██$col7█▀█$col1██▄  $col2▄█$col7█ █$col2██$col7█ █$col2█▄  $col4▄█$col7█ █$col4██$col7█ █$col4█▄  $col5▄█$col7█ █$col5██$col7█ █$col5█▄  $col6▄██$col7█▀█$col6██$col7█▀█$col6▄
 $col3███████▀      $col7▄▄  ▄▄  ▄▄   $col1█$col7▄▄█$col1██$col7▄▄█$col1███  $col2██$col7███$col2██$col7███$col2██  $col4██$col7███$col4██$col7███$col4██  $col5██$col7███$col5██$col7███$col5██  $col6███$col7█▄▄$col6██$col7█▄▄$col6█
 $col3███████▄      $col7▀▀  ▀▀  ▀▀   $col1████████████  $col2████████████  $col4████████████  $col5████████████  $col6████████████  
 $col3▀█████████▄▄               $col1██▀██▀▀██▀██  $col2██▀██▀▀██▀██  $col4██▀██▀▀██▀██  $col5██▀██▀▀██▀██  $col6██▀██▀▀██▀██
 $col3  ▀███████▀                $col1▀   ▀  ▀   ▀  $col2▀   ▀  ▀   ▀  $col4▀   ▀  ▀   ▀  $col5▀   ▀  ▀   ▀  $col6▀   ▀  ▀   ▀ 
$rst
EOF
