#!/bin/sh
# Author: lantlos
# Modified by: MarceliGG

initializeANSI()
{
  esc=""

  blackf="${esc}[30m";   redf="${esc}[31m";    greenf="${esc}[32m"
  yellowf="${esc}[33m"   bluef="${esc}[34m";   purplef="${esc}[35m"
  cyanf="${esc}[36m";    whitef="${esc}[37m"

  reset="${esc}[0m"
  bg="${esc}[38;5;239m"
}

initializeANSI

cat << EOF

      ${blackf}██████            ${blackf}██████
    ${blackf}██${reset}██${reset}${bluef}██${reset}${blackf}██${reset}${bluef}██${reset}        ${blackf}██${reset}██${reset}${bluef}██${reset}${blackf}██${reset}${bluef}██
    ${blackf}██${reset}██${bluef}██${reset}${blackf}██${reset}${bluef}██        ${blackf}██${reset}██${bluef}██${reset}${blackf}██${reset}${bluef}██
    ${blackf}██████${reset}${yellowf}██████${reset}      ${blackf}██████${reset}${purplef}██████
    ${blackf}████${reset}████${blackf}██${reset}        ${blackf}████${reset}████${blackf}██
  ${blackf}████${reset}████████${blackf}██${reset}    ${blackf}████${reset}████████${blackf}██
  ${blackf}████${reset}████████${blackf}██${reset}    ${blackf}████${reset}████████${blackf}██
  ${blackf}████${reset}████████${blackf}██${reset}    ${blackf}████${reset}████████${blackf}██
    ${blackf}████${reset}████${blackf}██${reset}        ${blackf}████${reset}████${blackf}██
   ${blackf}███${reset}${yellowf}███   ${yellowf}████${reset}     ${blackf}███${reset}${purplef}███   ${purplef}████
                                  
EOF
