hl.on("hyprland.start", function () 
  hl.exec_cmd("qs")
  hl.exec_cmd("lxqt-policykit-agent")
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("wk-clip-persist --clipboard both")
end)
