hl.on("hyprland.start", function () 
  hl.exec_cmd("qs")
  hl.exec_cmd("lxqt-policykit-agent")
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 24")
  hl.exec_cmd("wk-clip-persist --clipboard both")
  hl.exec_cmd("sleep 3 && keepassxc --minimized")
end)

hl.env("EDITOR", "helix")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
