#!/bin/sh
# Author: MarceliGG

col1=$'\x1b[38;2;17;114;122;m'
col2=$'\x1b[38;2;255;255;255;m'
col3=$'\x1b[38;2;74;237;217;m'
col4=$'\x1b[38;2;18;54;13;m'
col5=$'\x1b[38;2;161;251;232;m'
col6=$'\x1b[38;2;26;170;167;m'
col7=$'\x1b[38;2;32;197;181;m'
rst=$'\e[0m'
cat << EOF

          $col1████████
        $col1██$col2████████$col1██
      $col1██$col2██$col3██████$col5██$col2██$col4██
    $col1██$col2██$col3██$col5████$col2██$col3██████$col4██
    $col1██$col2██$col3██$col2██$col2██$col2████$col3████$col4██
  $col1██$col2██$col3██$col2██$col3████$col5████$col6██$col7██$col6██$col4██
  $col1██$col2██$col3██$col2██$col3██$col5██████$col1██$col7██$col6██$col4██
  $col1██$col2████$col6██$col5██████$col3██$col1██$col6████$col4██
  $col1██$col2██$col3████$col6████████$col7████$col1██$col4██
    $col4██$col3██$col6██$col7████████$col6██$col7██$col4██
    $col4██$col3██$col6██$col7████████$col6██$col2██$col4██
      $col4██$col1██$col3████$col2████$col7██$col4██
        $col4████████████
$rst
EOF