[language.python]
filetypes = ["python"]
roots = ["venv", "main.py", ".git"]
command = "pylsp"
# args = ["--stdio"]

[language.ccls]
filetypes = ["c", "cpp"]
roots = ["main.c", "main.cpp", ".git"]
command = "ccls"
