[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
documentFormatting = false

# [language-server.jdtls]
# args = ["-Djava.import.generatesMetadataFilesAtProjectRoot=false"]
# command = "jdtls"

# [[language]]
# name = "java"

[language-server.hx-lsp]
command = "hx-lsp"

[[language]]
name = "python"
language-servers = ["pyright"]
formatter = { command = "autopep8", args = ["--max-line-length", "200", "-"]}

# [[language]]
# name = "jsonc"
# formatter = { command = "biome", args = ["format", "--indent-style=space", "--stdin-file-path", "json.jsonc"] }

# [[language]]
# name = "json"
# formatter = { command = "biome", args = ["format", "--indent-style=space", "--stdin-file-path", "json.jsonc"] }

# [[language]]
# name = "html"
# language-servers = [ "vscode-html-language-server", "hx-lsp" ]

# [[language]]
# name = "cpp"
# language-servers = [ "clangd", "hx-lsp" ]

# [[language]]
# name = "c"
# language-servers = [ "clangd", "hx-lsp" ]


